name: Build and Push Docker Image

on:
    push:
        tags:
            - '*'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -
                name: Build and Export to Docker
                uses: docker/build-push-action@v5
                with:
                    context: .
                    load: true
                    tags: |
                        ghcr.io/pplmx/infinity:latest
                        ghcr.io/pplmx/infinity:0.1.0-beta
            -
                name: Test it before Push
                run: |
                    docker run --rm ghcr.io/pplmx/infinity:latest
                    docker run --rm ghcr.io/pplmx/infinity:0.1.0-beta
            -
                name: Build and Push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    platforms: linux/amd64,linux/arm64
                    push: true
                    tags: |
                        ghcr.io/pplmx/infinity:latest
                        ghcr.io/pplmx/infinity:0.1.0-beta
